from text_rpg_maker import *  
game = Game('test')
race = game.ask_choices("Pick your race", ["Elf", "Ogre", "Human"])
game.say(race)
name = input("What's your name traveler ?:")
game.say(name)
file = open("characters.txt", "a")
file.write(str(race))
file.write(":")
file.write(name + "\n")
file.write("---" + "\n")
file.close()